export const brands = [
  { label: 'Selecione a marca', value: '', id: 0 },
  { label: 'Admiral', value: 'Admiral', id: 1 },
  { label: 'Agratto', value: 'Agratto', id: 2 },
  { label: 'Britania', value: 'Britania', id: 3 },
  { label: 'Carrier', value: 'Carrier', id: 4 },
  { label: 'Comfee', value: 'Comfee', id: 5 },
  { label: 'Consul', value: 'Consul', id: 6 },
  { label: 'Daikin', value: 'Daikin', id: 7 },
  { label: 'Delonghi', value: 'Delonghi', id: 8 },
  { label: 'Electrolux', value: 'Electrolux', id: 9 },
  { label: 'Elgin', value: 'Elgin', id: 10 },
  { label: 'Fontaine', value: 'Fontaine', id: 11 },
  { label: 'Fujitsu', value: 'Fujitsu', id: 12 },
  { label: 'Gree', value: 'Gree', id: 13 },
  { label: 'Haier', value: 'Haier', id: 14 },
  { label: 'Hitachi', value: 'Hitachi', id: 15 },
  { label: 'Komeco', value: 'Komeco', id: 16 },
  { label: 'LG', value: 'LG', id: 17 },
  { label: 'Midea', value: 'Midea', id: 18 },
  { label: 'Maxiflex', value: 'Maxiflex', id: 19 },
  { label: 'Panasonic', value: 'Panasonic', id: 20 },
  { label: 'Phaser', value: 'Phaser', id: 21 },
  { label: 'Philco', value: 'Philco', id: 22 },
  { label: 'Rinetto', value: 'Rinetto', id: 23 },
  { label: 'Samsung', value: 'Samsung', id: 24 },
  { label: 'Splendid', value: 'Splendid', id: 25 },
  { label: 'Springer', value: 'Springer', id: 26 },
  { label: 'TCL', value: 'TCL', id: 27 },
  { label: 'Tempstar', value: 'Tempstar', id: 28 },
  { label: 'Trane', value: 'Trane', id: 29 },
  { label: 'Vogga', value: 'Vogga', id: 30 },
  { label: 'York', value: 'York', id: 31 },
]
