export enum UserRolesDTO {
  ADMIN = 'ADMIN',
  CLIENT_HOME = 'CLIENT_HOME',
  CLIENT_BUSINESS = 'CLIENT_BUSINESS',
  SERVICE_PROVIDER_TECHNICIAN = 'SERVICE_PROVIDER_TECHNICIAN',
  SERVICE_PROVIDER_COMPANY = 'SERVICE_PROVIDER_COMPANY',
}
